version: '3.1'
services:
    jenkins:
        build: .
        image: jenkins-arm64:latest
        ports:
            - '8080:8080'
        secrets:
            - jenkins_adm_password
        environment:
            - USE_SECRET=S
            - JENKINS_ADMIN_ID=admin
            - JENKINS_ADMIN_PASSWORD=/run/secrets/jenkins_adm_password
secrets:
    jenkins_adm_password:
        file: ./password.txt
